version: '3.9'

services:
  adonis-app:
    container_name: Adonis
    build: .
    ports:
      - '3333:3333'
    volumes:
      - .:/home/node/app
      - ./node_modules:/home/node/app/node_modules
    links:
      - postgresql-app
    depends_on:
      - postgresql-app

  postgresql-app:
    container_name: Postgres
    image: postgres:latest
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: mesa
